version: '3.4'

networks:
  dev:
    driver: bridge

services:
  hycommerce_db:
    image: postgres:latest
    container_name: hycommerce_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hyCommerceDB
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev

  hycommerce_blob_storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: hycommerce_blob_storage
    volumes:
      - ./.containers/blob_storage/data:/data
    ports:
      - "10000:10000"
    command: "azurite-blob --blobHost 0.0.0.0 -l /data" 

volumes:
  app_data: